---
apiVersion: v1
kind: ConfigMap
metadata:
  name: caddyfile
  namespace: searxng
data:
  Caddyfile: |
    search.heffner.live {
        reverse_proxy whoogle:5000
        encode gzip
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: caddy
  namespace: searxng
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caddy
  template:
    metadata:
      labels:
        app: caddy
    spec:
      containers:
      - name: caddy
        image: caddy:latest
        ports:
        - containerPort: 80
        - containerPort: 443
        volumeMounts:
        - name: caddyfile-volume
          mountPath: /etc/caddy/Caddyfile
          subPath: Caddyfile
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
      volumes:
      - name: caddyfile-volume
        configMap:
          name: caddyfile
---
apiVersion: v1
kind: Service
metadata:
  name: caddy
  namespace: searxng
spec:
  selector:
    app: caddy
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoogle
  namespace: searxng
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whoogle
  template:
    metadata:
      labels:
        app: whoogle
    spec:
      containers:
      - name: whoogle
        image: benbusby/whoogle-search:latest
        ports:
        - containerPort: 5000
        env: []
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: whoogle
  namespace: searxng
spec:
  selector:
    app: whoogle
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: whoogle-ingress
  namespace: searxng
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: search.heffner.live
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: caddy
                port:
                  number: 80
  tls:
    - hosts:
        - search.heffner.live
      secretName: search-heffner-live-tls
