apiVersion: apps/v1
kind: Deployment
metadata:
  name: radar
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: radar
  template:
    metadata:
      labels:
        app: radar
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: radar
              topologyKey: kubernetes.io/hostname
      containers:
        - name: radar
          image: technotuba/radar@sha256:641fba77f00fd6735fa5335461700c79a0cdde55f3aacd08c26e4efdb02beeae
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          envFrom:
            - secretRef:
                name: radar
---
apiVersion: v1
kind: Service
metadata:
  name: radar
spec:
  selector:
    app: radar
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: radar
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: radar
