apiVersion: apps/v1
kind: Deployment
metadata:
  name: radar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radar
  template:
    metadata:
      labels:
        app: radar
    spec:
      containers:
        - name: radar
          image: technotuba/radar:latest
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: radar
---
apiVersion: v1
kind: Service
metadata:
  name: radar
spec:
  selector:
    app: radar
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
  type: NodePort
