apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-radar-config
  namespace: cloudflared
  labels:
    app.kubernetes.io/name: cloudflared-radar
    app.kubernetes.io/part-of: edge
data:
  config.yml: |
    tunnel: 596de255-9aa5-45e9-8edc-9e6c5199d938
    credentials-file: /etc/cloudflared-creds/credentials.json
    metrics: 0.0.0.0:2000
    no-autoupdate: true
    protocol: auto
    loglevel: info
    grace-period: 30s
    ingress:
      - hostname: radar.heffner.live
        service: http://radar.radar.svc.cluster.local:8080
      - service: http_status:404
