apiVersion: apps/v1
kind: Deployment
metadata:
  name: pythonwebapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pythonwebapp
  template:
    metadata:
      labels:
        app: pythonwebapp
    spec:
      containers:
      - name: pythonwebapp
        image: technotuba/pythonwebappv3
        ports:
        - containerPort: 443
        volumeMounts:
        - name: tls-certs
          mountPath: /home/huey
          readOnly: true
      volumes:
        - name: tls-certs
          secret:
            secretName: pythonwebapp-tls
---
apiVersion: v1
kind: Service
metadata:
  name: pythonwebapp
spec:
  selector:
    app: pythonwebapp
  ports:
    - name: tls
      protocol: TCP
      port: 443
      targetPort: 443
  type: ClusterIP
