name: Write kube cert backup

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Write kube-root-ca.crt from GitHub Secret
        run: |
          echo "${{ secrets.KUBE_ROOT_CA_CRT }}" | base64 --decode > kube-root-ca.crt