name: Switch NGINX Service to Blue

on:
  workflow_dispatch:

jobs:
  switch-service-to-blue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Change only the Service selector from green to blue in nginx-green.yaml
        run: |
          awk '{
            if (!done && $0 ~ /^ *version: green/) {
              sub(/version: green/, "version: blue")
              done=1
            }
            print
          }' nginx-green.yaml > tmp.yaml && mv tmp.yaml nginx-green.yaml

      - name: Change only the Service selector from green to blue in nginx-blue.yaml
        run: |
          awk '{
            if (!done && $0 ~ /^ *version: green/) {
              sub(/version: green/, "version: blue")
              done=1
            }
            print
          }' nginx-blue.yaml > tmp.yaml && mv tmp.yaml nginx-blue.yaml

      - name: Commit and push changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add nginx-green.yaml nginx-blue.yaml
          git commit -m "chore: switch nginx service selector to blue" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}
