name: Push GREEN silo to latest image

on:
  workflow_dispatch:
    
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Change only the Service selector from green to blue in nginx-green.yaml
        run: |
          awk '{
            if (!done && $0 ~ /^ *version: blue/) {
              sub(/version: blue/, "version: green")
              done=1
            }
            print
          }' nginx-green.yaml > tmp.yaml && mv tmp.yaml nginx-green.yaml

      - name: Change only the Service selector from green to blue in nginx-blue.yaml
        run: |
          awk '{
            if (!done && $0 ~ /^ *version: blue/) {
              sub(/version: blue/, "version: green")
              done=1
            }
            print
          }' nginx-blue.yaml > tmp.yaml && mv tmp.yaml nginx-blue.yaml

      - name: Update blue deployment to use previous image
        run: sed -i 's#technotuba/nginx:[^"]*#technotuba/nginx:${{ steps.tags.outputs.LATEST }}#g' nginx-blue.yaml

      - name: Commit and push updated YAMLs
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add nginx-green.yaml nginx-blue.yaml
          git commit -m "chore: update deployment images to latest and previous" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}
