name: Push GREEN silo to latest image

on:
  workflow_dispatch:

jobs:
  switch-service-to-green:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Change only the Service selector from green to blue in nginx-service.yaml
        run: |
          awk '{
            if (!done && $0 ~ /^ *version: blue/) {
              sub(/version: blue/, "version: green")
              done=1
            }
            print
          }' shared/nginx-service.yaml > tmp.yaml && mv tmp.yaml shared/nginx-service.yaml

      - name: Update blue deployment to latest
        run: sed -i 's#technotuba/nginx:[^"]*#technotuba/nginx:latest#g' nginx-blue.yaml

      - name: Commit and push updated YAMLs
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add shared/nginx-service.yaml
          git commit -m "chore: update deployment images to latest and previous" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}
