name: Retag DockerHub Latest

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  retag-latest:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get current year and month
        id: date
        run: echo "TAG=v$(date +'%Y.%m')" >> $GITHUB_OUTPUT

      - name: Pull latest image
        run: docker pull technotuba/nginx:latest

      - name: Tag image with year.month
        run: docker tag technotuba/nginx:latest technotuba/nginx:${{ steps.date.outputs.TAG }}

      - name: Push new tag
        run: docker push technotuba/nginx:${{ steps.date.outputs.TAG }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: pip install requests
      
      - name: Generate Dockerfile with latest versions
        run: python .github/scripts/generate_dockerfile.py

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: technotuba/nginx:latest
          
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Pull latest changes
        run: git pull --rebase

      - name: Update green deployment to use latest image
        run: sed -i 's#***/nginx:[^"]*#***/nginx:latest#g' nginx-green.yaml

      - name: Update blue deployment to use versioned image
        run: sed -i "s#***/nginx:[^\"']*#***/nginx:v2025.06#g" nginx-blue.yaml

      - name: Commit and push updated YAMLs
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add nginx-green.yaml nginx-blue.yaml
          git commit -m "chore: update deployment images to latest and v2025.06" || echo "No changes to commit"
          git push
